Traceback (most recent call last):
  File "/home/okz21/spearmint-install/Spearmint-d9e95208e7a242669e2f76bfc838db79d740e8ab/spearmint/launcher.py", line 192, in <module>
    from spearmint.utils.database.mongodb import MongoDB
  File "/home/okz21/spearmint-install/Spearmint-d9e95208e7a242669e2f76bfc838db79d740e8ab/spearmint/utils/database/mongodb.py", line 187, in <module>
    import pymongo
  File "/anaconda/envs/py35/lib/python3.5/site-packages/pymongo/__init__.py", line 77, in <module>
    from pymongo.collection import ReturnDocument
  File "/anaconda/envs/py35/lib/python3.5/site-packages/pymongo/collection.py", line 29, in <module>
    from pymongo import (common,
  File "/anaconda/envs/py35/lib/python3.5/site-packages/pymongo/common.py", line 27, in <module>
    from pymongo.auth import MECHANISMS
  File "/anaconda/envs/py35/lib/python3.5/site-packages/pymongo/auth.py", line 46, in <module>
    from pymongo.errors import ConfigurationError, OperationFailure
  File "/anaconda/envs/py35/lib/python3.5/site-packages/pymongo/errors.py", line 20, in <module>
    from ssl import CertificateError
  File "/anaconda/envs/py35/lib/python3.5/ssl.py", line 91, in <module>
    import ipaddress
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 693, in exec_module
  File "<frozen importlib._bootstrap_external>", line 797, in get_code
  File "<frozen importlib._bootstrap_external>", line 508, in _compile_bytecode
KeyboardInterrupt
